/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author SENA
 */
public class vistaprincipal extends javax.swing.JFrame {

    /**
     * Creates new form interfaz
     */
    public vistaprincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLlogosena = new javax.swing.JLabel();
        jLtitulo2 = new javax.swing.JLabel();
        jBcrear = new javax.swing.JButton();
        jBver = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLtitulo = new javax.swing.JLabel();
        jLfondotitulo2 = new javax.swing.JLabel();
        jLfondotitulo = new javax.swing.JLabel();
        jTextbuscar = new javax.swing.JTextField();
        jLfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 340, 20));

        jLlogosena.setIcon(new javax.swing.ImageIcon("D:\\proyectosham\\src\\main\\java\\images\\Mi proyecto.png")); // NOI18N
        getContentPane().add(jLlogosena, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, 110, 100));

        jLtitulo2.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        jLtitulo2.setText("Que desea hacer?");
        getContentPane().add(jLtitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 170, 30));

        jBcrear.setBackground(new java.awt.Color(0, 177, 0));
        jBcrear.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jBcrear.setText("Crear Horarios");
        jBcrear.setBorderPainted(false);
        jBcrear.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBcrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcrearActionPerformed(evt);
            }
        });
        getContentPane().add(jBcrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 160, 40));

        jBver.setBackground(new java.awt.Color(0, 177, 0));
        jBver.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jBver.setText("Ver Horarios ");
        jBver.setBorderPainted(false);
        jBver.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBver.setMaximumSize(new java.awt.Dimension(114, 23));
        jBver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBverActionPerformed(evt);
            }
        });
        getContentPane().add(jBver, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 160, 40));

        jButton1.setIcon(new javax.swing.ImageIcon("D:\\proyectosham\\src\\main\\java\\images\\searcher_magnifyng_glass_search_locate_find_icon_123813.png")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, 40, 40));

        jLtitulo.setFont(new java.awt.Font("Verdana", 1, 48)); // NOI18N
        jLtitulo.setText("Bienvenido a SHAM");
        getContentPane().add(jLtitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 530, 70));

        jLfondotitulo2.setBackground(new java.awt.Color(204, 204, 204));
        jLfondotitulo2.setIcon(new javax.swing.ImageIcon("D:\\proyectosham\\src\\main\\java\\images\\fondogris.png")); // NOI18N
        jLfondotitulo2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLfondotitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 240, 310));

        jLfondotitulo.setBackground(new java.awt.Color(255, 255, 255));
        jLfondotitulo.setIcon(new javax.swing.ImageIcon("D:\\proyectosham\\src\\main\\java\\images\\515958.jpg")); // NOI18N
        getContentPane().add(jLfondotitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 100));

        jTextbuscar.setBackground(new java.awt.Color(204, 204, 204));
        jTextbuscar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jTextbuscar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(240, 240, 240), 1, true));
        jTextbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextbuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jTextbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 340, 40));

        jLfondo.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLfondo.setIcon(new javax.swing.ImageIcon("D:\\proyectosham\\src\\main\\java\\images\\fondoverde1.png")); // NOI18N
        getContentPane().add(jLfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 490, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBverActionPerformed

    private void jBcrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcrearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBcrearActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextbuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextbuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaprincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jBcrear;
    public javax.swing.JButton jButton1;
    public javax.swing.JButton jBver;
    public javax.swing.JLabel jLfondo;
    public javax.swing.JLabel jLfondotitulo;
    public javax.swing.JLabel jLfondotitulo2;
    public javax.swing.JLabel jLlogosena;
    public javax.swing.JLabel jLtitulo;
    public javax.swing.JLabel jLtitulo2;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JTextField jTextbuscar;
    // End of variables declaration//GEN-END:variables
}
